book/urls.py
from django.urls import path, include
from .views import *


app_name = "book"
urlpatterns = [
    path('', search_book, name="searchbook"),
    path('add-fav', add_fav, name="add-fav"),
    path('del-fav', del_fav, name="del-fav"),
    path('my-fav', my_fav, name="fav"),
]

pro_story6/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views
from app_signup.views import logout_view, login_view

urlpatterns = [
    path('admin/', admin.site.urls),

    path('',include('app_story6.urls')),
    path('places/', include('places.urls')),
    path('books/', include('book.urls')),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('auth/', include('social_django.urls', namespace='social')),
]

book/models.py
from django.db import models
# Create your models here.
class FavBook(models.Model):
    title = models.CharField(max_length = 100)
    img = models.CharField(max_length=200)
    link = models.CharField(max_length = 200)
    author = models.CharField(max_length=200)

book/forms.py
from django import forms


class SearchForm(forms.Form):
    search_attrs = {
        'type': 'text',
        'class': 'form-control',
        'placeholder':'Search book',
    }
    title = forms.CharField(max_length = 300, label='', widget=forms.TextInput(attrs=search_attrs))

book/views.py
from django.shortcuts import render
from django.http import JsonResponse, HttpResponse, HttpResponseRedirect
from django.core import serializers
from .forms import SearchForm
from .models import FavBook
# from app_signup.models import Profile
from django.views.decorators.csrf import csrf_exempt
import requests
import json
# Create your views here.
def search_book(request):
    response = {}
    response['form'] = SearchForm()
    response['fav'] = FavBook.objects.all().count
    response['data'] = None
    if request.method == 'POST':
        form = SearchForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            search = cd['title']
            URL = "https://www.googleapis.com/books/v1/volumes?q=" + search
            get_json = requests.get(URL).json()
            json_dict = json.dumps(get_json)
            response['data'] = json_dict
            if request.user.is_authenticated:
                if 'counter' not in request.session:
                    request.session['counter'] = 0
                count = request.session['counter']
                response['counter'] = count
                if 'nama' not in request.session:
                    request.session['nama'] = request.user.username
                if 'email' not in request.session:
                    request.session['email'] = request.user.email
        return render(request, "searchbook.html", response)
    else:
        if request.user.is_authenticated:
            print(request.user.username)
            if 'nama' not in request.session:
                    request.session['nama'] = request.user.username
            if 'email' not in request.session:
                request.session['email'] = request.user.email
            if 'counter' not in request.session:
                request.session['counter'] = 0
            count = request.session['counter']
            response['counter'] = count
            print(dict(request.session))
        return render(request, "searchbook.html", response)
def add_fav(request):
    if request.user.is_authenticated:
        # print(dict(request.session))
        # judul = request.GET.get('judul', None)
        # link = request.GET.get('link', None)
        # img = request.GET.get('img', None)
        # author = request.GET.get('author', None)
        # fav = FavBook(title=judul, img=img, link=link, author=author)
        # fav.save()
        print(dict(request.session))
        request.session['counter'] = request.session['counter'] + 1
        print(dict(request.session))
    else:
        pass
    return HttpResponse(request.session['counter'], content_type='application/json')
@csrf_exempt
def del_fav(request):
    if request.user.is_authenticated:
        # judul = request.POST['judul']
        # cui = FavBook.objects.filter(title=judul)
        # print(cui)
        # cui.delete()
        # request.session['counter'] -= 1
        # data = request.session
        # data_json = serializers.serialize('json', data)
        request.session['counter'] = request.session['counter'] - 1
        print(dict(request.session))
        return HttpResponse(request.session['counter'], content_type='aplication/json')
def my_fav(request):
    response = {}
    response['data'] = FavBook.objects.all()
    return render(request, "fav.html", response)

book/templates/fav.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <link rel="apple-touch-icon" sizes="180x180" href="{% static 'apple-touch-icon.png'%}">
        <link rel="icon" type="image/png" sizes="32x32" href="{% static 'favicon-32x32.png'%}">
        <link rel="icon" type="image/png" sizes="16x16" href="{% static 'favicon-16x16.png'%}">
        <meta name="theme-color" content="#ffffff">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">
        <title>Search Book</title>
        <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js" integrity="sha256-VazP97ZCwtekAsvgPBSUwPFKdrwD3unUfSGVYrahUqU=" crossorigin="anonymous"></script>
    </head>
    <body>
        <div class="container">
            <div class="row">
                <h1>Your Favorite Book</h1>
                <div class="col-md-12">
                    <table id = "result" class="table table-stripped">
                        <thead>
                            <tr>
                                <th scope="col">#</th>
                                <th scope="col">Book</th>
                                <th scope="col">Title</th>
                                <th scope="col">Author</th>
                            </tr>
                        </thead>
                        <tbody>
                            {%for item in data%}
                            <tr>
                                <th>{{forloop.counter}}</th>
                                <td><a target="_blank" href="{{item.link}}"><img src="{{item.img}}" title="{{item.title}}"></a></td>
                                <td>{{item.title}}</td>
                                <td>{{item.author}}</td>
                            </tr>
                            {%endfor%}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        
    </body>
</html>

book/templates/searchbook.html
{%load static%}
{%load staticfiles%}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <link rel="apple-touch-icon" sizes="180x180" href="{% static 'apple-touch-icon.png'%}">
        <link rel="icon" type="image/png" sizes="32x32" href="{% static 'favicon-32x32.png'%}">
        <link rel="icon" type="image/png" sizes="16x16" href="{% static 'favicon-16x16.png'%}">
        <meta name="theme-color" content="#ffffff">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">
        <link href="https://fonts.googleapis.com/css?family=Raleway:600,700" rel="stylesheet">
        <title>Search Book</title>
        <style>
            body {
                font-family: 'Raleway', sans-serif;
                font-weight: 700;
            }
        </style>
        <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js" integrity="sha256-VazP97ZCwtekAsvgPBSUwPFKdrwD3unUfSGVYrahUqU=" crossorigin="anonymous"></script>
    </head>
    <body>
        {%if user.is_authenticated%}
        <header class = "m-3" style="display: flex;">
            <p id ="{{user.username}}">Hello, {{ user.username }}</p>
            <a style="color: black"href="{%url 'book:fav'%}"><i class="fas fa-star"></i></a><span id = "count">{{counter}}</span>
            <a href= "{% url 'logout'%}">Log Out</a>
        </header>
        {%else%}<header><a href="{% url 'social:begin' 'google-oauth2' %}">Login with Google</a><br></header>
        {%endif%}
        <div class="container">
            <div class="row">
                <h1>Search Book</h1>
                <div class="col-md-12">
                    <div class="text-center">
                        <form id="searchbook" method="POST" action= "{% url 'book:searchbook'%}">
                            {% csrf_token %}
                            {{form}}
                            <button class="btn btn-dark">Submit</button>
                        </form>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <table id = "result" class="table table-stripped">
                        
                    </table>
                </div>
            </div>
        </div>
        {%if data%}
        <script>
            var user = "{{ user.username }}"
            var result = JSON.parse("{{data|escapejs}}");
            $("#result").append("<thead><tr><th scope=\"col\">No</th><th scope=\"col\">Favorite</th><th scope=\"col\">Book</th><th scope=\"col\">Title</th><th scope=\"col\">Author</th></tr></thead><tbody>");
            for (i=0; i<result.items.length; i++) {
                var judult = "<td class=\"judul\">" + result.items[i].volumeInfo.title + "</td>";
                var authort = "<td class=\"author\">"+ result.items[i].volumeInfo.authors + "</td>";
                var nomor = "<tr id=\"item-"+ i+1 + "\">";
                var roww = "<th scope="+ "\"row\">" + (i+1) + "</th>";
                var star = "<td><i title=\"Favorite\" class=\"fav far fa-star\"></td>"
                var link = "<td><a target=\"_blank\" href=\""+ result.items[i].volumeInfo.infoLink + "\">"+ "<img src=\"" + result.items[i].volumeInfo.imageLinks.thumbnail + "\">" + "</a></td>"
                $("#result").append(nomor + roww + star + link + judult + authort + "</tr>");
                }
                $("#result").append("</tbody>");
        </script>
        {%endif%}
        <script src="{%static 'searchbook.js'%}"></script>
    </body>
</html>