app_story6/urls.py
from django.urls import path
from .views import *

app_name = "app_story6"
urlpatterns = [
    path('landingpage', landing_page, name="landingpage"),
    path('add_status',add_status, name="add_status"),
    path('', profile, name="hi-here"),
    path('subscribe', subscribe, name="subscribe"),
    path('validate', validate),
    path('success', success, name="success"),
    path('allsubs', getallsubs, name="allsubs"),
    path('subscribers', subspage, name="subscribers"),
    path('delsub', delsub),
]

book/urls.py
from django.urls import path, include
from .views import *


app_name = "book"
urlpatterns = [
    path('', search_book, name="searchbook"),
    path('add-fav', add_fav, name="add-fav"),
    path('del-fav', del_fav, name="del-fav"),
    path('my-fav', my_fav, name="fav"),
]

pro_story6/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views
from app_signup.views import logout_view, login_view

urlpatterns = [
    path('admin/', admin.site.urls),

    path('',include('app_story6.urls')),
    path('places/', include('places.urls')),
    path('books/', include('book.urls')),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('auth/', include('social_django.urls', namespace='social')),
]

app_story6/models.py
from django.db import models

# Create your models here.
class Status(models.Model):
    message = models.CharField(max_length = 300)
    created_at = models.DateTimeField(auto_now_add=True, editable=False, null=False, blank=False)


class Subscriber(models.Model):
    name = models.CharField(max_length = 50)
    password = models.CharField(max_length = 20)
    email = models.CharField(max_length = 50)

app_story6/forms.py
from django import forms


class StatusForm(forms.Form):
    stats_attrs = {
        'type': 'text',
        'class': 'form-control',
        'placeholder':'Status',
    }
    message = forms.CharField(max_length = 300, widget=forms.TextInput(attrs=stats_attrs))

class SubscribeForm(forms.Form):
    email_attrs = {
        'type': 'text',
        'class': 'form-control',
        'placeholder':'Example: hira@gmail.com',
    }
    name_attrs = {
        'type': 'text',
        'class': 'form-control',
        'placeholder':'Full Name',
    }
    pass_attrs = {
        'type': 'password',
        'class': 'form-control',
        'placeholder':'Password',
    }
    name = forms.CharField(max_length = 50, error_messages={"required": "Please enter your name"}, widget = forms.TextInput(attrs=name_attrs))
    password = forms.CharField(max_length = 20, min_length=6, widget = forms.PasswordInput(attrs=pass_attrs), error_messages={"min_length": "password must be longer than 5 characters"})
    email = forms.EmailField(error_messages={"required": "Please enter a valid email"}, max_length=50, widget=forms.TextInput(attrs=email_attrs))

app_story6/views.py
from django.shortcuts import render
from .forms import StatusForm, SubscribeForm
from django.http import HttpResponseRedirect
from .models import Status, Subscriber
from django.http import JsonResponse, HttpResponse
from django.views.decorators.csrf import csrf_exempt
from django.core import serializers
from django.forms.models import model_to_dict
import json

response = {}
# Create your views here.

def landing_page(request):
    response = {}
    all_stats = Status.objects.all()
    response['all_stats'] = all_stats
    
    response['forms'] = StatusForm()
    

    return render(request, 'landingpage.html', response)

def add_status(request):
    response = {}
    form = StatusForm(request.POST or None)
    if(request.method == 'POST' and form.is_valid()):
        response['message'] = request.POST['message']
        stats = Status(message=response['message'])
        stats.save()
        return HttpResponseRedirect('/landingpage')
    else:
        return HttpResponseRedirect('/landingpage')

def profile(request):
    response = {}
    return render(request, 'profile.html', response)

  
def subscribe(request):
    response = {}
    response["forms"] = SubscribeForm()
    return render(request, 'subscribe.html', response)


@csrf_exempt
def validate(request):
    email = request.POST.get("email")
    data = {'not_valid': Subscriber.objects.filter(email__iexact=email).exists()
    }
    return JsonResponse(data)

def success(request):
    submited_form = SubscribeForm(request.POST or None)
    if (submited_form.is_valid()):
        cd = submited_form.cleaned_data
        new_subscriber = Subscriber(name=cd['name'], password=cd['password'], email=cd['email'])
        new_subscriber.save()
        data = {'name': cd['name'], 'password': cd['password'], 'email': cd['email']}
    return JsonResponse(data)

def getallsubs(request):
    data_json = serializers.serialize('json', Subscriber.objects.all())
    return HttpResponse(data_json, content_type='aplication/json')

def subspage(request):
    return render(request, "allsubs.html") 
@csrf_exempt
def delsub(request):
    if 'email' in request.POST:
        print('mantap')
        email = request.POST['email']
        lele = Subscriber.objects.filter(email=email)
        lele.delete()
        return HttpResponseRedirect("/allsubs")
    else:
        print('ngapa DAH')
        return HttpResponseRedirect("/allsubs")

app_story6/templates/allsubs.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <link rel="apple-touch-icon" sizes="180x180" href="{% static 'apple-touch-icon.png'%}">
        <link rel="icon" type="image/png" sizes="32x32" href="{% static 'favicon-32x32.png'%}">
        <link rel="icon" type="image/png" sizes="16x16" href="{% static 'favicon-16x16.png'%}">
        <meta name="theme-color" content="#ffffff">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
        <link href="https://fonts.googleapis.com/css?family=Raleway:600,700" rel="stylesheet">
        <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
        <title>Subscribe to here-a</title>
        <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js" integrity="sha256-VazP97ZCwtekAsvgPBSUwPFKdrwD3unUfSGVYrahUqU=" crossorigin="anonymous"></script>
        <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
        <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/sweetalert2@7.29.0/dist/sweetalert2.min.css">
        <script src="https://cdn.jsdelivr.net/npm/sweetalert2@7.29.0/dist/sweetalert2.all.min.js"></script>
        <script src="http://cdnjs.cloudflare.com/ajax/libs/modernizr/2.8.2/modernizr.js"></script>
        
    </head>
    <body>
        <div class="container">
            <div class = "text-center  m-4">
                    <h1 class=" text-white" id="yyy"><a href="{%url 'app_story6:hi-here' %}" style="background-color:transparent;" ><span class="text-white" style="text-decoration:underline #A56AA3">Here-a</span></a> Subscribers</h1>
            </div>
                
            <div class="row">

                <div id= "allsubs"class="col-md-12">

                </div>
            </div>
        </div>
        <script>
            $(document).ready(function() {
                
                $.ajax({
                    url:"/allsubs",
                    method: 'GET',
                    dataType: 'html',
                    success: function(data){
                        var parse = JSON.parse(data); 
                        console.log(parse);
                        for(i = 0; i< parse.length; i++) {
                            var card = "<div id =\"" + parse[i].fields.email + "\" class=\"card\" style=\"width: 30rem;\"><div class=\"card-body-allsubs\"><h5 class=\"card-title\">" +parse[i].fields.name+ "</h5><button type=\"button\" class=\"unsubs btn btn-danger\">Unsubscribe</button></div></div>";
                            $("#allsubs").append(card);
                        }
                        $(".unsubs").each(function() {
                            $(this).click(function () {
                                var emailx = $(this).closest('.card').attr('id');
                                console.log(emailx); 
                                $.ajax({
                                    url:"/delsub",
                                    data: {email: emailx},
                                    method: 'POST',
                                    dataType: 'json',
                                    success: function() {
                                        swal({
                                            title: "Success",
                                            text: 'You can subscribe again later',
                                            type: 'success',
                                            showConfirmButton: false,
                                            timer: 2500
                                            }).then(function() {
                                                window.location = "/subscribers"
                                            });   
                                    }
                                });
                            }
                               
                            );
                        });
                    }
                });
            });
        
        </script>
    </body>
</html>

app_story6/templates/landingpage.html
{%load static%}

<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <link rel="apple-touch-icon" sizes="180x180" href="{% static 'apple-touch-icon.png'%}">
        <link rel="icon" type="image/png" sizes="32x32" href="{% static 'favicon-32x32.png'%}">
        <link rel="icon" type="image/png" sizes="16x16" href="{% static 'favicon-16x16.png'%}">
        <meta name="theme-color" content="#ffffff">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
        <script src="https://ajax.aspnetcdn.com/ajax/jQuery/jquery-3.3.1.min.js"></script>
        <title>Landing Page</title>
    </head>
    <body style ="background-color: #edeff0" class= 'text-center'>
        <div class="container">
            <div class = "row">
                <div class= "col-3"></div>
                <div class= "col-6">
                    <h1>Hello, Apa kabar?</h1>
                    <form action="add_status" method="POST">
                        <div class="form-group">
                                {% csrf_token %}
                                {{ forms }}
                        </div>
                        <button type="submit" class="btn btn-dark">Submit</button>
                    </form>
                    
                </div>
                <div class = "col-2"></div>
            </div>
            <div class="row">
                <div class="col-3"></div>
                <div class='col-6'>
                    {% if all_stats %}
                    {% for stats in all_stats %}
                    <div class="flex-item">
                        <h2 style="color:#3e474f">{{stats.message}}</h2>
                        <p>at {{ stats.created_at }}</p>
                    </div>
                    {% endfor %}
                    {% endif %}
                    
                </div>
            </div>
        </div>
        
    </body>
</html>

app_story6/templates/subscribe.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <link rel="apple-touch-icon" sizes="180x180" href="{% static 'apple-touch-icon.png'%}">
        <link rel="icon" type="image/png" sizes="32x32" href="{% static 'favicon-32x32.png'%}">
        <link rel="icon" type="image/png" sizes="16x16" href="{% static 'favicon-16x16.png'%}">
        <meta name="theme-color" content="#ffffff">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
        <link href="https://fonts.googleapis.com/css?family=Raleway:600,700" rel="stylesheet">
        <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/sweetalert2@7.29.0/dist/sweetalert2.min.css">
        <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
        <title>Subscribe to here-a</title>
        <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js" integrity="sha256-VazP97ZCwtekAsvgPBSUwPFKdrwD3unUfSGVYrahUqU=" crossorigin="anonymous"></script>
        <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
        <script src="http://cdnjs.cloudflare.com/ajax/libs/modernizr/2.8.2/modernizr.js"></script>
    </head>
    <body >
        
        <div class ="container">
            <h1 class="text-center text-white m-2"id="title">Subscribe to <a href="{%url 'app_story6:hi-here' %}" class="text-white"style="background-color:transparent;" ><span style="text-decoration:underline #A56AA3">Here-a</span></a></h1>
            <div class="row m-5">
                <div class="col-md-4"></div>
                
                <div class="col-md-4" id="subscribepage">
                    <form method="POST">
                        <div class="form-group">
                            {%csrf_token%}
                            {{forms}}
                        </div>
                        <button id= "submit_subscribe" disabled= "disabled" type="submit" class = "btn btn-dark">Subscribe</button>
                        
                    </form>
                </div>
                <div class="col-md-4"></div>
            </div>
        </div>
        <script src="https://cdn.jsdelivr.net/npm/sweetalert2@7.29.0/dist/sweetalert2.all.min.js"></script>
        <script src="{%static 'subscribe.js'%}"></script>
    </body>
</html>