book/urls.py
from django.urls import path, include
from .views import *


app_name = "book"
urlpatterns = [
    path('', search_book, name="searchbook"),
    path('add-fav', add_fav, name="add-fav"),
    path('del-fav', del_fav, name="del-fav"),
    path('my-fav', my_fav, name="fav"),
]

places/urls.py
from django.urls import path, include
from .views import *

app_name = "places"
urlpatterns = [
    path('<str:place>', render_place, name="place"),
    path('', awal_place, name="awal"),
]

pro_story6/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views
from app_signup.views import logout_view, login_view

urlpatterns = [
    path('admin/', admin.site.urls),

    path('',include('app_story6.urls')),
    path('places/', include('places.urls')),
    path('books/', include('book.urls')),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('auth/', include('social_django.urls', namespace='social')),
]

places/models.py
from django.db import models

# Create your models here.
class Places(models.Model):
    place = models.TextField(max_length=30, primary_key=True)
    img = models.CharField(max_length=200)
    desc = models.TextField(max_length=5000)
    date_modified = models.DateTimeField(auto_now_add=True, editable=False, null=False, blank=False)

class Record(models.Model):
    nama = models.CharField(max_length=50)
    place = models.TextField(max_length=50)
    date_modified =  models.DateTimeField(auto_now_add=True, editable=False, null=False, blank=False)

places/views.py
from django.shortcuts import render
from django.shortcuts import get_object_or_404
from .models import Places, Record
from django.contrib.auth.decorators import login_required
# Create your views here.
response = {}
def awal_place(request):
    places = Places.objects.all()
    response['places'] = places
    return render(request, "home.html", response)


@login_required
def render_place(request, place):
    program = get_object_or_404(Places, pk=place)
    nama = request.user.first_name + request.user.last_name
    print(request.user.username)
    obj = Record(nama=request.user.first_name + request.user.last_name, place=place)
    obj.save()
    response['program'] = program
    return render(request, "places.html", response)

places/templates/home.html
{%load static%}
<!DOCTYPE html>
<html>
    <head>
        <!-- Global site tag (gtag.js) - Google Analytics -->
        <script async src="https://www.googletagmanager.com/gtag/js?id=UA-129830132-1"></script>
        <script>
        window.dataLayer = window.dataLayer || [];
        function gtag(){dataLayer.push(arguments);}
        gtag('js', new Date());

        gtag('config', 'UA-129830132-1');
        </script>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
        <link href="https://fonts.googleapis.com/css?family=Roboto|Roboto+Condensed:300" rel="stylesheet">
        <link rel="stylesheet" href="{% static 'places.css'%}">
        <title>places.</title>
        <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js" integrity="sha256-VazP97ZCwtekAsvgPBSUwPFKdrwD3unUfSGVYrahUqU=" crossorigin="anonymous"></script>
    </head>
    <body>
        <div class="container">
            <header class="text-right">
                {%if user.is_authenticated%}
                <a href="{%url 'logout'%}">logout</a>
                {%else%}
                <a href="{% url 'social:begin' 'google-oauth2' %}">login</a>
                {%endif%}
            </header>
            <div class="text-center p-3">
                <h1>places that echo your name</h1>
                <p id="subtitle">raw thoughts, its either i don't mention it or i told the whole truth.
                they're online because it's a platform for myself to heal, and as a lesson on how i (will hopefully)
                recover from a past event. </p>
            </div>
            <div class="row">
                {%if user.is_authenticated%}
                    {%for i in places%}
                    <div class="col-12 col-md-4 p-3">
                        <a href="/places/{{i.place}}">
                            <img src="{{i.img}}" title="{{i.place}}" class="img-fluid">
                        </a>  
                    </div>
                    {%endfor%}
                {%endif%}
            </div>
            
        </div>
        
    </body>
</html>

places/templates/places.html
{%load static%}
<!DOCTYPE html>
<html>
    <head>
        <!-- Global site tag (gtag.js) - Google Analytics -->
        <script async src="https://www.googletagmanager.com/gtag/js?id=UA-129830132-1"></script>
        <script>
        window.dataLayer = window.dataLayer || [];
        function gtag(){dataLayer.push(arguments);}
        gtag('js', new Date());

        gtag('config', 'UA-129830132-1');
        </script>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
        <link href="https://fonts.googleapis.com/css?family=Roboto|Roboto+Condensed:300" rel="stylesheet">
        <link rel="stylesheet" href="{% static 'places.css'%}">
        <title>places: {{program.place}}</title>
        <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js" integrity="sha256-VazP97ZCwtekAsvgPBSUwPFKdrwD3unUfSGVYrahUqU=" crossorigin="anonymous"></script>
    </head>
    <body>
        <div class="container-fluid">
            <div class="text-center p-3">
                <a href="{% url 'places:awal'%}">
                    <h1>places: {{program.place}}</h1>
                </a>  
            </div>
            
            <div id="things" class="row p-5">
                <div class="col-md-4 p-0">
                    <img class="img-fluid position-sticky" src="{{program.img}}">
                </div>
                <div class="col-md-8">
                    <p>{{program.desc}}</p>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                        <div class="text-center">
                                <p>at {{program.date_modified}}</p>
                            </div>
                </div>
                
                
            </div>
        </div>
    </body>
</html>